import argparse
import os
import sys
from config import PLANNED_TASK_PATH, TASK_EXECUTION_RESULT_PATH, TASK_EXECUTION_LOG_PATH

# 假设 agents 目录下有 agent1_task_planner.py 和 agent2_executor.py
from agents.agent1_task_planner import Agent1TaskPlanner
from agents.agent2_task_executor import Agent2TaskExecutor


def main():
    parser = argparse.ArgumentParser(description="Run AutoDroid multi-agent pipeline")
    parser.add_argument(
        "--task",
        type=str,
        required=True,
        help="The complex task to execute (e.g., 'Find accommodation in Tokyo')"
    )

    parser.add_argument(
        "--ui-tree-file",
        type=str,
        required=True,
        help="UI tree JSON/JS file path used by Agent1"
    )

    parser.add_argument(
        "--target-apk",
        type=str,
        required=True,
        help="Target APK executed by Agent2"
    )


    args = parser.parse_args()

    task_desc = args.task
    ui_tree_path = args.ui_tree_file
    apk_path = args.target_apk


    if not os.path.isfile(ui_tree_path):
        print(f"[Error] UI tree file not found: {ui_tree_path}")
        sys.exit(1)

    # # === Agent1: 任务分解 ===
    # print("[Main] Running Agent1 (task planning)...")
    # agent1 = Agent1TaskPlanner(task_desc=task_desc, ui_tree_path= ui_tree_path, planned_task_path=PLANNED_TASK_PATH)
    # planned_task_file = agent1.run()
    # print(f"[Main] Agent1 output actions: {planned_task_file}")

    # if not planned_task_file:
    #     print("[Main] No actions generated by Agent1. Aborting.")
    #     sys.exit(1)
    planned_task_file = None

    # # === Agent2: 执行任务 ===
    print("[Main] Running Agent2 (task execution)...")
    agent2 = Agent2TaskExecutor(
        apk_path=apk_path,
        output_dir=TASK_EXECUTION_RESULT_PATH,
        task_str=task_desc,
        log_path=TASK_EXECUTION_LOG_PATH,
        instruction_path=planned_task_file
    )
    agent2.run()
    print("[Main] Pipeline finished.")


if __name__ == "__main__":
    main()
