import argparse
import os
import sys
from config import PLANNED_TASK_PATH, TASK_EXECUTION_RESULT_PATH, TASK_EXECUTION_LOG_PATH, APP_EXPLORATION_LOG_PATH, APP_EXPLORATION_RESULT_PATH

# 假设 agents 目录下有 agent1_task_planner.py 和 agent2_executor.py
from agents.agent1_task_planner import Agent1TaskPlanner
from agents.agent2_task_executor import Agent2TaskExecutor
from agents.agent3_app_explorer import Agent3AppExplorer


def main():
    parser = argparse.ArgumentParser(description="Run multi-agent pipeline with two modes")

    # 互斥参数组：探索模式或执行模式
    mode_group = parser.add_mutually_exclusive_group(required=True)
    
    # 探索模式参数
    mode_group.add_argument(
        "--explore",
        action="store_true",
        help="Run in app exploration mode"
    )
    
    # 执行模式参数
    mode_group.add_argument(
        "--execute",
        action="store_true",
        help="Run in task execution mode"
    )

    
    # 共用参数
    parser.add_argument(
        "--target-apk",
        type=str,
        required=True,
        help="Target APK path"
    )
    
    # # 探索模式专用参数
    # parser.add_argument(
    #     "--output-path",
    #     type=str,
    #     help="Output directory for exploration results (required in explore mode)"
    # )
    
    # 执行模式专用参数
    parser.add_argument(
        "--task",
        type=str,
        help="The complex task to execute (required in execute mode)"
    )
    parser.add_argument(
        "--ui-tree-file",
        type=str,
        help="UI tree JSON/JS file path used by Agent1 (required in execute mode)"
    )


    args = parser.parse_args()

    apk_path = args.target_apk

    if args.explore:
        # === 探索模式 ===
        # if not args.output_path:
        #     print("[Error] --output-path is required in explore mode")
        #     sys.exit(1)
            
        print("[Main] Running in exploration mode...")
        agent3 = Agent3AppExplorer(
            apk_path=apk_path,
            output_dir=APP_EXPLORATION_RESULT_PATH,
            log_path=APP_EXPLORATION_LOG_PATH
        )
        agent3.run()


    elif args.execute:
        # === 执行模式 ===
        if not all([args.task, args.ui_tree_file]):
            print("[Error] --task and --ui-tree-file are required in execute mode")
            sys.exit(1)
            
        if not os.path.isfile(args.ui_tree_file):
            print(f"[Error] UI tree file not found: {args.ui_tree_file}")
            sys.exit(1)

        print("[Main] Running in execution mode...")
        
        # Agent1: 任务分解
        print("[Main] Running Agent1 (task planning)...")
        agent1 = Agent1TaskPlanner(
            task_desc=args.task,
            ui_tree_path=args.ui_tree_file,
            planned_task_path=PLANNED_TASK_PATH
        )
        planned_task_file = agent1.run()
        print(f"[Main] Agent1 output actions: {planned_task_file}")

        if not planned_task_file:
            print("[Main] No actions generated by Agent1. Aborting.")
            sys.exit(1)

        # Agent2: 执行任务
        print("[Main] Running Agent2 (task execution)...")
        agent2 = Agent2TaskExecutor(
            apk_path=apk_path,
            output_dir=TASK_EXECUTION_RESULT_PATH,
            task_str=args.task,
            log_path=TASK_EXECUTION_LOG_PATH,
            instruction_path=planned_task_file
        )
        agent2.run()

    print("[Main] Pipeline finished.")


if __name__ == "__main__":
    main()
