import argparse
import os
import sys

# 假设 agents 目录下有 agent1_task_planner.py 和 agent2_executor.py
from agents.agent1_task_planner import Agent1TaskPlanner
# from agents import agent2_executor as agent2


def main():
    parser = argparse.ArgumentParser(description="Run AutoDroid multi-agent pipeline")
    parser.add_argument(
        "--task",
        type=str,
        required=True,
        help="The complex task to execute (e.g., 'Find accommodation in Tokyo')"
    )

    parser.add_argument(
        "--ui-tree-file",
        type=str,
        required=True,
        help="UI tree JSON/JS file path used by Agent1"
    )
    args = parser.parse_args()

    task_desc = args.task
    ui_tree_path = args.ui_tree_file


    if not os.path.isfile(ui_tree_path):
        print(f"[Error] UI tree file not found: {ui_tree_path}")
        sys.exit(1)

    # === Agent1: 任务分解 ===
    print("[Main] Running Agent1 (task planning)...")
    agent1 = Agent1TaskPlanner(task_desc=task_desc, ui_tree_path= ui_tree_path)
    actions = agent1.run()
    print(f"[Main] Agent1 output actions: {actions}")

    if not actions:
        print("[Main] No actions generated by Agent1. Aborting.")
        sys.exit(1)

    # # === Agent2: 执行任务 ===
    # print("[Main] Running Agent2 (execution)...")
    # result = agent2.run_executor(actions, func_doc_dir)
    # print(f"[Main] Agent2 result: {result}")


if __name__ == "__main__":
    main()
